#pragma once

#include "rock/parse.h"
#include "rock/starting_position.h"
#include "rock/types.h"

inline constexpr rock::Board random_game_boards_5_moves[] = {
    rock::parse_literal_board("   wwwww"
                              "b      b"
                              "bwb    b"
                              "b      b"
                              "       b"
                              "b   w   "
                              "b      b"
                              " www bw "),
    rock::parse_literal_board("ww ww  w"
                              "b      b"
                              "bw     b"
                              "b  b   b"
                              "       b"
                              "b  bw b "
                              "b       "
                              " www  w "),
    rock::parse_literal_board("ww ww  w"
                              "b    b  "
                              "bw     w"
                              "b  b   b"
                              "       b"
                              "b  b    "
                              "b       "
                              " www  b "),
    rock::parse_literal_board("bwbww   "
                              "b    b  "
                              "   w   w"
                              "b      b"
                              "       b"
                              "b  b b  "
                              "        "
                              " www  b "),
    rock::parse_literal_board("bwbww   "
                              "b b  b  "
                              "   w w  "
                              "     b b"
                              "       b"
                              "w  b    "
                              "  w     "
                              " w    b "),
    rock::parse_literal_board("bwb w   "
                              "b    b  "
                              "   w w  "
                              "  b  b b"
                              "       b"
                              "w       "
                              "w      b"
                              " w      "),
    rock::parse_literal_board("b b w   "
                              "b  b b  "
                              "   w w  "
                              "  b   wb"
                              "     b b"
                              "w       "
                              "w       "
                              " w      "),
    rock::parse_literal_board("bwb w   "
                              "b  b b  "
                              "     w  "
                              "    b w "
                              "     bb "
                              "w     b "
                              " w      "
                              " w      "),
    rock::parse_literal_board("bwb w   "
                              "b b     "
                              "w    w  "
                              " b  b w "
                              "     bb "
                              "      b "
                              "w  w    "
                              "        "),
    rock::parse_literal_board("bwb w  w"
                              "bbb     "
                              "w       "
                              "    w   "
                              "      bb"
                              "     b  "
                              "w  w    "
                              "        "),
};

inline constexpr rock::Board random_game_boards_10_moves[] = {
    rock::parse_literal_board("bwb w  w"
                              "bb    w "
                              "w   b   "
                              "b      b"
                              "      b "
                              "        "
                              "w  w    "
                              "        "),
    rock::parse_literal_board("bwb    b"
                              "bb w    "
                              "w   b  b"
                              "b       "
                              "        "
                              "        "
                              "   www  "
                              "        "),
    rock::parse_literal_board(" wb    b"
                              " bb     "
                              "w bwb w "
                              "        "
                              "  w    b"
                              "        "
                              "     w  "
                              " b      "),
    rock::parse_literal_board(" w     b"
                              " bb     "
                              "  b   w "
                              "w  b   w"
                              "     bb "
                              "        "
                              "        "
                              " b  w   "),
    rock::parse_literal_board("  w     "
                              " b      "
                              "  bwbbw "
                              "     w  "
                              "    b b "
                              "        "
                              "   b    "
                              "        "),
    rock::parse_literal_board("w w   w "
                              " b      "
                              "  b bb  "
                              "     w  "
                              "   b  b "
                              "        "
                              "      b "
                              "        "),
    rock::parse_literal_board("  ww  w "
                              " b  w   "
                              "  b    b"
                              "        "
                              "      b "
                              "        "
                              "      b "
                              "        "),
    rock::parse_literal_board("  ww    "
                              " b      "
                              "   w   b"
                              "        "
                              "      b "
                              "     w  "
                              "  b  b  "
                              "        "),
    rock::parse_literal_board("  w     "
                              " bw    b"
                              "        "
                              "        "
                              "      b "
                              "   w  w "
                              "  b     "
                              "   b    "),
    rock::parse_literal_board("        "
                              "       b"
                              "        "
                              " ww     "
                              "b       "
                              "   w  w "
                              "b   b   "
                              "   b    "),
};

inline constexpr rock::Board assorted_random_game_boards[] = {
    rock::parse_literal_board("b     bw"
                              " w      "
                              "   w    "
                              "    b   "
                              "    b   "
                              "  bw w  "
                              " wbw  bb"
                              "bb      "),
    rock::parse_literal_board(" w   ww "
                              "       b"
                              "      wb"
                              "b      b"
                              "b      b"
                              "bbw w  w"
                              "b      b"
                              " wbw  w "),
    rock::parse_literal_board(" w  www "
                              "b    b  "
                              " w w   b"
                              "  b    b"
                              "b   b  b"
                              " w     b"
                              "b      b"
                              " wwwww  "),
    rock::parse_literal_board("bw w  w "
                              "  bb    "
                              "   ww  w"
                              "  w    b"
                              "bb  b  b"
                              " w  w   "
                              "        "
                              "     bwb"),
    rock::parse_literal_board("ww ww   "
                              "bb     w"
                              "  b  w  "
                              "        "
                              "     bwb"
                              "w   w  b"
                              "  w b   "
                              "    b b "),
    rock::parse_literal_board(" www ww "
                              "b    w b"
                              "      b "
                              "   b b  "
                              " b  bw b"
                              "w     w "
                              "  bwb   "
                              "   w w  "),
    rock::parse_literal_board(" www  w "
                              "b    b b"
                              "bw     b"
                              "     b  "
                              " w     b"
                              "  b  ww "
                              "bw      "
                              "w  bww  "),
    rock::parse_literal_board(" w    ww"
                              " b  b   "
                              "  b w  b"
                              "b      b"
                              "b      b"
                              "    w ww"
                              " b     b"
                              " bww  w "),
};
