#pragma once

#include "types.h"
#include <utility>

namespace rock
{

auto generate_moves(Board const& board, Player player) -> MoveList;
auto count_moves(Board const& board, Player player_to_move, int level = 1) -> std::size_t;
auto is_legal_move(Move, Board const&, Player) -> bool;

auto are_pieces_all_together(BitBoard board) -> bool;
auto get_game_outcome(Board const&, Player to_move) -> GameOutcome;

struct MoveRecommendation
{
    Move move;
    double score;
};

/**
 * Player to move, positive result is good for player
 */
auto recommend_move(Board const& board, Player player) -> MoveRecommendation;
auto evaluate_position(Board const& board, Player player) -> double;

/**
 * Normalize a score generated by the above functions so that positive always
 * means that White is winning
 */
auto normalize_score(double score, Player player) -> double;

}  // namespace rock
